---
sidebar: sidebar 
permalink: vsphere-kubernetes-service/vks-overview.html 
keywords: vks, vSphere Kubernetes Service, ONTAP, kubernetes, overview 
summary: 了解 vSphere Kubernetes Service 及其如何与 NetApp ONTAP 集成以支持容器化工作负载。 
---
= 了解结合 NetApp ONTAP 的 VMware vSphere Kubernetes 服务
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware vSphere Kubernetes 服务 (VKS) 是 VMware 提供的托管 Kubernetes 产品，使组织能够使用 Kubernetes 部署、管理和扩展容器化应用程序。与 NetApp ONTAP 存储配合使用，VKS 为云原生工作负载提供企业级持久性、性能和数据管理。

VKS 嵌入 VMware Cloud Foundation (VCF)，符合上游 CNCF Kubernetes，确保与更广泛的 Kubernetes 生态系统和工具的兼容性。



[[key-features-of-vsphere-kubernetes-service]]
== vSphere Kubernetes Service 的主要功能

. *托管 Kubernetes 集群：* vSphere Kubernetes Service 简化了 Kubernetes 集群的部署和管理。它可以自动执行集群创建、升级、扩展和监控等任务。
. *与 VMware 基础设施集成：* VKS 与 VMware vSphere、NSX-T 和其他 VMware 解决方案无缝集成，使组织能够利用其现有的 VMware 基础设施来处理 Kubernetes 工作负载。
. *多云和混合云支持：* vSphere Kubernetes Service 支持在私有云、公共云（例如 AWS、Azure、Google Cloud）和混合云环境中进行部署，为组织提供管理应用程序的灵活性。
. *内置安全性：* VKS 包括基于角色的访问控制 (RBAC)、策略实施以及与 VMware NSX 集成以实现网络安全等安全功能。
. *支持 Kubernetes 生态系统：* VKS 支持完整的上游 Kubernetes API，确保跨环境的可移植性以及与更广泛的 Kubernetes 生态系统的兼容性，包括用于服务网格的 Istio、用于监控的 Prometheus 以及其他 CNCF 认证工具。组织可以将标准的 Kubernetes 技能和集成直接应用于 VKS 集群。
. *开发人员友好型工具：* VKS 支持标准的 Kubernetes 开发人员工作流程，包括 CI/CD 管道、GitOps 实践以及 kubectl 和 Helm 等工具，使开发团队能够在无需学习专有接口的情况下构建和部署容器化应用程序。
. *可扩展性和高可用性：* VKS 提供自动扩展和容错等功能，以确保应用程序保持高可用性和高性能。
. *可观察性和监控：* VKS 与标准的 Kubernetes 兼容监控工具集成，可提供对集群和应用程序性能的实时洞察。




[[use-cases-for-vsphere-kubernetes-service]]
== vSphere Kubernetes Service 的使用案例

. *应用程序现代化：* 组织可以通过容器化旧应用程序并将其部署在由 VKS 管理的 Kubernetes 集群上来实现旧应用程序的现代化。
. *DevOps 支持：* VKS 通过提供自动化、CI/CD 集成和便于开发人员使用的工具来支持 DevOps 工作流程。
. *混合云部署：* 企业可以使用 VKS 跨本地和云环境部署 Kubernetes 集群，实现一致的操作。
. *微服务架构：* VKS 支持基于微服务的应用程序开发，允许团队构建和扩展分布式系统。

