---
sidebar: sidebar 
permalink: tanzu/vtwn-solution-overview.html 
keywords: VMware Tanzu, Tanzu, DevOps, Netapp, Trident, Trident Protect 
summary: '本参考文档提供了不同版本的 VMware Tanzu Kubernetes 解决方案的部署验证，这些解决方案经 NetApp 验证，可以作为 Tanzu Kubernetes Grid (TKG)、Tanzu Kubernetes Grid Service (TKGS) 或 Tanzu Kubernetes Grid Integrated (TKGI) 部署在NetApp不同的数据中心环境中。' 
---
= NVA-1166：VMware Tanzu 与NetApp合作
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


NetApp 的Alan Cowles 和 Nikhil M Kulkarni

[role="lead"]
本参考文档提供了不同版本的 VMware Tanzu Kubernetes 解决方案的部署验证，这些解决方案经 NetApp 验证，可以作为 Tanzu Kubernetes Grid (TKG)、Tanzu Kubernetes Grid Service (TKGS) 或 Tanzu Kubernetes Grid Integrated (TKGI) 部署在NetApp不同的数据中心环境中。它还描述了与NetApp存储系统和Trident存储编排器的存储集成，用于管理持久存储，以及Trident Protect 用于使用该持久存储备份和克隆有状态应用程序。最后，该文档提供了解决方案集成和验证的视频演示。



== 使用情形

VMware Tanzu 与NetApp解决方案的架构旨在通过以下用例为客户提供卓越的价值：

* 易于部署和管理部署在 VMware vSphere 上并与NetApp存储系统集成的 VMware Tanzu Kubernetes Grid 产品。
* 企业容器和虚拟化工作负载与 VMware Tanzu Kubernetes Grid 产品的综合实力。
* 真实的配置和用例突出显示了 VMware Tanzu 与NetApp存储和NetApp Trident产品套件一起使用时的功能。
* 使用Trident Protect 对部署在 VMware Tanzu Kubernetes Grid 集群上且数据驻留在NetApp存储系统上的容器化工作负载进行应用程序一致性保护或迁移。




== 商业价值

企业越来越多地采用 DevOps 实践来创建新产品、缩短发布周期并快速添加新功能。由于其固有的敏捷特性，容器和微服务在支持 DevOps 实践方面发挥着至关重要的作用。然而，在企业环境中以生产规模实践 DevOps 也面临着自身的挑战，并对底层基础设施提出了一定的要求，例如：

* 堆栈中所有层的高可用性
* 简化部署程序
* 无中断运行和升级
* API 驱动和可编程的基础设施，以跟上微服务的敏捷性
* 具有性能保证的多租户
* 能够同时运行虚拟化和容器化工作负载
* 能够根据工作负载需求独立扩展基础设施
* 能够在混合云模型中部署，容器可以在本地数据中心和云中运行。


VMware Tanzu 与NetApp共同承认这些挑战，并提出了一种解决方案，通过在客户选择的混合云环境中部署 VMware Tanzu Kubernetes 产品来帮助解决每个问题。



== 技术概述

VMware Tanzu 与NetApp解决方案由以下主要组件组成：



=== VMware Tanzu Kubernetes 平台

VMware Tanzu 具有多种版本， NetApp的解决方案工程团队已在我们的实验室中对其进行了验证。每个 Tanzu 版本都与NetApp存储产品组合成功集成，并且每个版本都可以帮助满足特定的基础设施需求。以下重点介绍了本文档中描述的 Tanzu 每个版本的功能和产品。

*VMware Tanzu Kubernetes 网格 (TKG)*

* 在 VMware vSphere 环境中部署的标准上游 Kubernetes 环境。
* 以前称为 Essential PKS（来自 Heptio 收购，2019 年 2 月）。
* TKG 部署了单独的管理集群实例，以支持 vSphere 6.7U3 及更高版本。
* TKG 部署也可以通过 AWS 或 Azure 部署在云中。
* 允许使用 Windows 或 Linux 工作节点（Ubuntu/Photon）。
* NSX-T、HA Proxy、AVI 网络或负载均衡器可用于控制平面。
* TKG 支持应用程序/数据平面的 MetalLB。
* 可以使用 vSphere CSI 以及第三方 CSI，如NetApp Trident。


*VMware Tanzu Kubernetes 网格服务 (TKGS)*

* 在 VMware vSphere 环境中部署的标准上游 Kubernetes 环境。
* 以前称为 Essential PKS（来自 Heptio 收购，2019 年 2 月）。
* TKGS 仅在 vSphere 7.0U1 及更高版本上与主管集群和工作负载集群一起部署。
* 允许使用 Windows 或 Linux 工作节点（Ubuntu/Photon）。
* NSX-T、HA Proxy、AVI 网络或负载均衡器可用于控制平面。
* TKGS 支持应用程序/数据平面的 MetalLB。
* 可以使用 vSphere CSI 以及第三方 CSI，如NetApp Trident。
* 通过 Tanzu 提供对 vSphere Pods 的支持，允许 Pod 直接在环境中启用的 ESXi 主机上运行。


VMWare Tanzu Kubernetes Grid 集成 (TKGI)

* 以前称为 Enterprise PKS（来自 Heptio 收购，2019 年 2 月）。
* 可以使用 NSX-T、HA Proxy 或 Avi。您还可以提供自己的负载均衡器。
* 从 vSphere 6.7U3 开始受支持，以及 AWS、Azure 和 GCP。
* 通过向导进行设置，以便于部署。
* 在由 BOSH 管理的受控不可变虚拟机中运行 Tanzu。
* 可以使用 vSphere CSI 以及第三方 CSI，如NetApp Trident （适用某些条件）。


带有 Tanzu 的 vSphere（vSphere Pod）

* vSphere 原生 pod 在基于光子的薄层中运行，并具有规定的虚拟硬件，以实现完全隔离。
* 需要 NSX-T，但允许额外的功能支持，例如 Harbor 映像注册表。
* 在 vSphere 7.0U1 及更高版本中使用 TKGS 等虚拟 Supervisor 集群进行部署和管理。直接在 ESXi 节点上运行 pod。
* 完全集成 vSphere，通过 vSphere 管理实现最高的可见性和控制。
* 基于 CRX 的隔离舱可实现最高级别的安全性。
* 仅支持 vSphere CSI 进行持久存储。不支持第三方存储协调器。




=== NetApp存储系统

NetApp拥有多种非常适合企业数据中心和混合云部署的存储系统。  NetApp产品组合包括NetApp ONTAP、 NetApp Element和NetApp e-Series 存储系统，所有这些系统都可以为容器化应用程序提供持久存储。

如需了解更多信息，请访问NetApp网站 https://www.netapp.com["此处"]。



=== NetApp存储集成

Trident是一个开源的、完全支持的存储编排器，适用于容器和 Kubernetes 发行版，包括 VMware Tanzu。

欲了解更多信息，请访问Trident网站 https://docs.netapp.com/us-en/trident/index.html["此处"]。



== 已验证版本的当前支持矩阵

|===


| 技术 | 目的 | 软件版本 


| NetApp ONTAP | 存储 | 9.9.1 


| NetApp Trident | 存储编排 | 22.04.0 


| VMware Tanzu Kubernetes 网格 | 容器编排 | 1.4+ 


.2+| VMware Tanzu Kubernetes 网格服务 .2+| 容器编排 | 0.0.15 [vSphere 命名空间] 


| 1.22.6 [主管集群 Kubernetes] 


| VMware Tanzu Kubernetes Grid集成 | 容器编排 | 1.13.3 


| VMware vSphere | 数据中心虚拟化 | 7.0U3 


| VMware NSX-T 数据中心 | 网络和安全 | 3.1.3 


| VMware NSX 高级负载均衡器 | 负载均衡器 | 20.1.3 
|===