---
sidebar: sidebar 
permalink: anthos/anthos-seesaw-lb.html 
summary: 本页详细介绍了 SeeSaw 负载均衡器的安装和配置说明。 
keywords: Anthos, GKE, Kubernetes, SeeSaw, LoadBalancer 
---
= 安装 SeeSaw 负载均衡器
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
本页列出了 SeeSaw 托管负载均衡器的安装和配置说明。

Seesaw 是安装在 VMware Anthos Clusters 环境中（版本 1.6 至 1.10）的默认托管网络负载均衡器。



== 安装 SeeSaw 负载均衡器

SeeSaw 负载均衡器与 VMware 上的 Anthos Clusters 完全集成，并作为管理员和用户集群设置的一部分执行自动部署。有文本块 `cluster.yaml`必须修改配置文件以提供负载均衡器信息，然后在集群部署之前还有一个额外的步骤，使用内置的 `gkectl`工具。


NOTE: SeeSaw 负载均衡器可以以 HA 或非 HA 模式部署。为了进行此验证，SeeSaw 负载均衡器以非 HA 模式部署，这是默认设置。出于生产目的， NetApp建议在 HA 配置中部署 SeeSaw，以实现容错和可靠性。



== 与 Anthos 集成

每个配置文件中都有一个部分，分别用于管理员集群和您选择部署的每个用户集群，以配置负载均衡器，以便由 Anthos On-Prem 管理。

以下文本是 GKE-Admin 集群分区配置的示例。需要取消注释和修改的值以粗体显示如下：

[listing, subs="+quotes,+verbatim"]
----
*loadBalancer:*
  # (Required) The VIPs to use for load balancing
  *vips:*
    # Used to connect to the Kubernetes API
    *controlPlaneVIP: "10.61.181.230"*
    # # (Optional) Used for admin cluster addons (needed for multi cluster features). Must
    # # be the same across clusters
    # # addonsVIP: ""
  # (Required) Which load balancer to use "F5BigIP" "Seesaw" or "ManualLB". Uncomment
  # the corresponding field below to provide the detailed spec
  *kind: Seesaw*
  # # (Required when using "ManualLB" kind) Specify pre-defined nodeports
  # manualLB:
  #   # NodePort for ingress service's http (only needed for user cluster)
  #   ingressHTTPNodePort: 0
  #   # NodePort for ingress service's https (only needed for user cluster)
  #   ingressHTTPSNodePort: 0
  #   # NodePort for control plane service
  #   controlPlaneNodePort: 30968
  #   # NodePort for addon service (only needed for admin cluster)
  #   addonsNodePort: 31405
  # # (Required when using "F5BigIP" kind) Specify the already-existing partition and
  # # credentials
  # f5BigIP:
  #   address:
  #   credentials:
  #     username:
  #     password:
  #   partition:
  #   # # (Optional) Specify a pool name if using SNAT
  #   # snatPoolName: ""
  # (Required when using "Seesaw" kind) Specify the Seesaw configs
  *seesaw:*
  # (Required) The absolute or relative path to the yaml file to use for IP allocation
  #  for LB VMs. Must contain one or two IPs.
  *ipBlockFilePath: "admin-seesaw-block.yaml"*
  #   (Required) The Virtual Router IDentifier of VRRP for the Seesaw group. Must
  #   be between 1-255 and unique in a VLAN.
    *vrid: 100*
  #   (Required) The IP announced by the master of Seesaw group
    *masterIP: "10.61.181.236"*
  #   (Required) The number CPUs per machine
    *cpus: 1*
  #   (Required) Memory size in MB per machine
    *memoryMB: 2048*
  #   (Optional) Network that the LB interface of Seesaw runs in (default: cluster
  #   network)
    *vCenter:*
  #   vSphere network name
      *networkName: VM_Network*
  #   (Optional) Run two LB VMs to achieve high availability (default: false)
    *enableHA: false*
----
SeeSaw 负载均衡器还具有单独的静态 `seesaw-block.yaml`您必须为每个集群部署提供该文件。该文件必须位于与 `cluster.yaml`部署文件，或者必须在上面的部分指定完整路径。

样本 `admin-seesaw-block.yaml`文件类似于以下脚本：

[listing, subs="+quotes,+verbatim"]
----
blocks:
  - netmask: "255.255.255.0"
    gateway: "10.63.172.1"
    ips:
    - ip: "10.63.172.152"
      hostname: "admin-seesaw-vm"
----

NOTE: 该文件提供了负载均衡器向底层集群提供的网络的网关和网络掩码，以及为运行负载均衡器而部署的虚拟机的管理 IP 和主机名。
